spring.application.name=vetrifresh

spring.datasource.url=jdbc:mysql://localhost:3306/vetrifresh
spring.datasource.username=root
spring.datasource.password=root

razorpay.key.id=rzp_test_SdeNVLRSGGaUsh
razorpay.key.secret=tlJcOhStMHDPjVff9iQaf5ZS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false


# Debug mode
debug=true


# Security logs (important for login)
logging.level.org.springframework.security=INFO

# Your app logs
logging.level.com.vetrifresh=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manikandarajnataraj@gmail.com
spring.mail.password=ckinhfjczwefkrva
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mvc.favicon.enabled=false


# razorpay.key.id=${RAZORPAY_KEY_ID}
# razorpay.key.secret=${RAZORPAY_KEY_SECRET}



# ----------------------------------render db------------------------------------------------------------
# # =======================================================================
# # ============================Environment Varibles========================
# spring.application.name=vetrifresh

# # ===== DATABASE =====
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # ===== JPA =====
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# # ===== THYMELEAF =====
# spring.thymeleaf.cache=true

# # ===== RAZORPAY =====
# razorpay.key.id=${RAZORPAY_KEY_ID}
# razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# # ===== MAIL =====
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=${MAIL_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# # ===== LOGGING =====
# logging.level.org.springframework.security=WARN
# logging.level.com.vetrifresh=INFO
# debug=false
# # ===== SERVER =====
# server.port=${PORT:10000}

# spring.jpa.hibernate.ddl-auto=update


# # ===== MISC =====
# spring.mvc.favicon.enabled=false